name: CI

on:
  push:
    paths-ignore:
      - '.gif/**'
      - 'EFI/**'
      - '**/*.md'
      - 'scripts/**'
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  build:
    uses: ./.github/workflows/_build.yml
