name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-rc[0-9]+'

permissions:
  contents: write   # create release
  actions: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  publish:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    needs: [build]
    #environment: production         # require approvals in repo settings
    steps:
      - name: Download ISO from build
        uses: actions/download-artifact@v4
        with:
          name: cdrom.iso
          path: dist

      - name: Checksums
        run: |
          cd dist
          sha256sum cdrom.iso > cdrom.iso.sha256
          ls -lh

      - name: Create/Update Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          files: |
            dist/cdrom.iso
            dist/cdrom.iso.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
